export default{
	entries : 10,
	search : '',
	users : {},
	user : {},
	profile:{},
	categories:{},
	subcategories:{},
	bookings:{},
	booking:{},
	cmss:{},
	cms:{},
	service:{},
	payments:{},
	packages:{},
	packag:{},
	subscriptions : {},
	subscription : {},
	wallets:{},
	feedbacks : {},
	feedback : {},
	admins : {},
	admin : {},
	home : {},
	notification_count : 0,
	bell_notifications : [],
	notifications : {},
	owners : {},
}